/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tbanftSol from "./TBANFT.sol";
export type { tbanftSol };
import type * as aave from "./aave";
export type { aave };
import type * as account from "./account";
export type { account };
import type * as erc6551 from "./erc6551";
export type { erc6551 };
import type * as lens from "./lens";
export type { lens };
