/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMockNFT,
  IMockNFTInterface,
} from "../../../contracts/TBANFT.sol/IMockNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMockNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IMockNFTInterface {
    return new utils.Interface(_abi) as IMockNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMockNFT {
    return new Contract(address, _abi, signerOrProvider) as IMockNFT;
  }
}
