/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMockNFT } from "./IMockNFT";
export type { IMockProfileCreationProxy } from "./IMockProfileCreationProxy";
export type { TBANFT } from "./TBANFT";
