/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Burnable__factory } from "./IERC20Burnable__factory";
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { IGhoToken__factory } from "./IGhoToken__factory";
