/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc6551AccountSol from "./IERC6551Account.sol";
export type { ierc6551AccountSol };
export type { IERC6551Registry } from "./IERC6551Registry";
